---
MD003:
  style: setext_with_atx_closed
MD013:
  line_length: 72
  heading_line_length: 72
  code_block_line_length: 72
  code_blocks: true
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false
MD033: false
MD041: false